name: city_of_chicago_modernization
version: 1.0.0
config-version: 2

profile: city_of_chicago_modernization

model-paths: ["models"]

models:
  city_of_chicago_modernization:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
